#!/usr/bin/env python3
"""
End-to-end test with full security enabled.

Tests the complete flow from server setup to client operations with
authentication, against the real FunkyGibbon server started by the repo-root
conftest (`server_url` / `auth_token` fixtures).

WHY THESE TESTS CHANGED
-----------------------
This module used to point at a hardcoded http://localhost:8000 and swallow
every failure into a `return False` that pytest ignores, so it reported success
whether or not anything worked -- and on a machine where something else owned
port 8000 it was authenticating against a stranger's server. It now talks only
to the session's own server on its private port, and asserts.

Guest access is obtained the way a guest really gets it: an admin asks the
server to mint a QR code. A guest token generated by a TokenManager inside the
test process is unknown to the server and could never verify, which is why the
old version could only ever "pass" by ignoring the failure.
"""

import asyncio
import json
import os
import tempfile
from datetime import timedelta
from pathlib import Path

import httpx
import pytest

from funkygibbon.auth import TokenManager
from blowingoff.client import BlowingOffClient

# Admin password the test server is configured with (see repo-root conftest.py).
ADMIN_PASSWORD = "TestAdmin#2024!"


@pytest.fixture
def client_db(tmp_path):
    """Path for a throwaway client database."""
    return str(tmp_path / "client.db")


async def _guest_qr_payload(server_url: str, auth_token: str, duration_hours: int = 1) -> str:
    """Ask the server (as admin) for a guest QR code and return its JSON payload.

    `custom_server` overrides the advertised hostname (the default is the
    mDNS name funkygibbon.local, which does not resolve here). The port in the
    payload comes from the server's own configuration, so the guest is pointed
    at the port this server is really listening on.
    """
    host = httpx.URL(server_url).host
    async with httpx.AsyncClient(base_url=server_url, timeout=10.0) as http:
        response = await http.post(
            "/api/v1/auth/guest/generate-qr",
            json={"duration_hours": duration_hours, "custom_server": host},
            headers={"Authorization": f"Bearer {auth_token}"},
        )
    assert response.status_code == 200, response.text
    qr_data = response.json()["qr_data"]
    assert qr_data["port"] == httpx.URL(server_url).port, (
        f"Server advertised port {qr_data['port']} in its guest QR code but is "
        f"listening on {httpx.URL(server_url).port}"
    )
    return json.dumps(qr_data)


@pytest.mark.asyncio
async def test_admin_authentication(server_url, client_db):
    """Test admin authentication flow."""
    client = BlowingOffClient(client_db)
    try:
        await client.connect(server_url=server_url, password=ADMIN_PASSWORD)

        assert client.check_admin_permission() is True
        assert client.check_write_permission() is True
    finally:
        await client.disconnect()


@pytest.mark.asyncio
async def test_admin_authentication_rejects_wrong_password(server_url, client_db):
    """A bad password must not yield a session."""
    client = BlowingOffClient(client_db)
    try:
        with pytest.raises(RuntimeError):
            await client.connect(server_url=server_url, password="not-the-admin-password")
    finally:
        await client.disconnect()


@pytest.mark.asyncio
async def test_guest_authentication(server_url, auth_token, client_db):
    """Test guest authentication via a server-issued QR code."""
    qr_string = await _guest_qr_payload(server_url, auth_token)

    client = BlowingOffClient(client_db)
    try:
        await client.connect(server_url=server_url, qr_data=qr_string)

        # Guests are read-only.
        assert client.check_write_permission() is False
        assert client.check_admin_permission() is False
    finally:
        await client.disconnect()


@pytest.mark.asyncio
async def test_operations_with_permissions(server_url, auth_token, tmp_path):
    """Test operations respecting permission levels."""
    from inbetweenies.models import EntityType

    # Admin client - should be able to write.
    admin_client = BlowingOffClient(str(tmp_path / "admin_ops.db"))
    try:
        await admin_client.connect(server_url=server_url, password=ADMIN_PASSWORD)
        assert admin_client.check_write_permission() is True

        result = await admin_client.execute_mcp_tool(
            "create_entity",
            entity_type=EntityType.HOME.value,
            name="Admin Test Home",
            content={"owner": "admin"},
        )
        assert result.get("success") is True
    finally:
        await admin_client.disconnect()

    # Guest client - read only.
    qr_string = await _guest_qr_payload(server_url, auth_token)
    guest_client = BlowingOffClient(str(tmp_path / "guest_ops.db"))
    try:
        await guest_client.connect(server_url=server_url, qr_data=qr_string)

        result = await guest_client.execute_mcp_tool("search_entities", query="Test", limit=10)
        assert result is not None

        assert guest_client.check_write_permission() is False
    finally:
        await guest_client.disconnect()


@pytest.mark.asyncio
async def test_token_expiration():
    """Test token expiration and refresh (pure token-manager behaviour)."""
    tm = TokenManager(secret_key=os.getenv("JWT_SECRET") or "e2e-token-expiry-test-secret")

    # Token that expires in 1 second.
    short_token = tm.create_token(
        user_id="test_user",
        role="guest",
        permissions=["read"],
        expires_delta=timedelta(seconds=1),
    )
    assert tm.verify_token(short_token) is not None

    await asyncio.sleep(2)
    assert tm.verify_token(short_token) is None, "Expired token still accepted"

    admin_token = tm.create_token(
        user_id="admin",
        role="admin",
        permissions=["read", "write", "delete", "configure"],
        expires_delta=timedelta(hours=1),
    )
    payload = tm.verify_token(admin_token)
    assert payload is not None
    assert payload.get("role") == "admin"


@pytest.mark.asyncio
async def test_concurrent_auth_sessions(server_url, tmp_path):
    """Test multiple concurrent authenticated sessions."""
    from inbetweenies.models import EntityType

    clients = []
    try:
        for i in range(3):
            client = BlowingOffClient(str(tmp_path / f"client_{i}.db"))
            await client.connect(
                server_url=server_url,
                password=ADMIN_PASSWORD,
                client_id=f"admin_client_{i}",
            )
            clients.append(client)

        assert len(clients) == 3

        for client in clients:
            result = await client.execute_mcp_tool("search_entities", query="test", limit=5)
            assert result["success"] is True
    finally:
        for client in clients:
            await client.disconnect()
